version: '3.9'

services:
  test-app:
    build: ../Customers.Api
    ports:
      - "7780:443"
      - "7779:80"
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=changeme
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_ENVIRONMENT=Production
      - CustomersApi_Database__ConnectionString=Host=test-db;Port=5432;Database=mydb;Username=course;Password=changeme  
      - CustomersApi_GitHub__ApiBaseUrl=http://localhost:9850
    depends_on:
      test-db:
        condition: service_healthy
  test-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=course
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=mydb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - '5435:5432'
